### ISSUE TITLE
Firefox transform

### ISSUE THREAD

**Issue by sidneyvav** [echa/ng-scrollable#10]
When do you have a flash object inside the div you're trying to use scrollable, the object disappears, it's caused by the CSS property used to scroll : transform: translate(X, Y);

This bug was noticed using Firefox 36.0.4

**Comment by echa** [comment]
Hey @sidneyvav. I just tried putting an iframed YouTube player that uses flash for playback inside ng-scrollable and it worked in FF 37. Seems like a Firefox issue on your OS. Did you try wmode="opaque" or wmode="transparent" on the Flash object?

**Comment by sidneyvav** [comment]
I tried wmode opaque, it solved the problem, many thanks!
