### ISSUE TITLE
touch support

### ISSUE THREAD

**Issue by thaasch** [echa/ng-scrollable#12]
Hey mate,
can you please add touch support for both directions? I also tried to use translate3d instead of translate and it was much more smooth when there are more Elements in the container.

I created a fork with basic touch support but its only for a specific use case maybe you can use it for reference :)

**Comment by echa** [comment]
Nice! Thanks for the translate3d hint. I've worked on a touch version myself, just didn't have time to integrate it yet. I'll have a look at your version :)

**Comment by echa** [comment]
Hey Timo, I just published ngScrollable 0.2.0 with touch support (but no MS Pointer support yet). Would be cool if you can give it a try. Let me know of any improvements you see.

**Comment by thaasch** [comment]
Hi Alexander, thanks for the fast development :) I tried out the example and most of the time the scrolling looks very smooth, but sometimes it stutters a bit. I used an iPad Air 1 for my tests. Maybe i can debug this issue tomorrow.

**Comment by echa** [comment]
:) thanks .. Actually I had done much of it in another project already. 

The stuttering I excperience as well. Even on desktop browsers using the wheel event. I'd appreciate if you could have a look.
