### ISSUE TITLE
Refresh() fails to scroll when bar isn't active

### ISSUE THREAD

**Issue by AnotherSymbiote** [echa/ng-scrollable#17]
This bug was introduced in commit 032691348b80b458468f53bd1c847078c3046d78.

See here: https://github.com/echa/ng-scrollable/blob/master/src/ng-scrollable.js#L260

Lines 252 & 260 have no effect.  To fix:
* Swap line 252 with 251.
* Swap line 260 with 259.

**Comment by AnotherSymbiote** [comment]
I fixed this & another similar bug in pull request #18.

**Comment by echa** [comment]
Thanks for spotting this :) It'll merge your PR.
