### ISSUE TITLE
Cant give a Spacebar in a textbox

### ISSUE THREAD

**Issue by Nirmalyas** [echa/ng-scrollable#2]
my code is below ===:
<div ng-scrollable id="dataLvls">
	<div ng-repeat="labelVal in arrLblVal">
		<input type="text" ng-model="labelVal.value" placeholder="Enter Data Label Name"  />
	</div>
</div>	

my problem is:
I cant give a space in that text box. like "firstname lastname". If I put the text box outside "ng-scrollable", then i can do it. In other areas the "ng-scrollable" is working superbly.

Thanks in advance.

**Comment by Nirmalyas** [comment]
Ok. I have done it myself.

**Comment by echa** [comment]
Hey Nirmalyas, even if you've solved it already I keep the solution for reference: 

ng-scrollable hooks the keydown event and filters out spacebar presses to mimic the typical scrolling behaviour of elements. To skip this on particular elements like input, textarea or regular div containers you must set those elements' `contenteditable` property to `true` like that:

```
<input contenteditable="true" type="text" />
```
Hope this helps.
