### ISSUE TITLE
Scrollbars do not appear if container has CSS max-height instead of height

### ISSUE THREAD

**Issue by progmars** [echa/ng-scrollable#21]
Could you please take a look at this plunkr:

http://plnkr.co/edit/hKrKxu2dKQNLDcNCpKvR?p=preview

Currently it does not show vertical scrollbar.

Only if I change style.css to have `height: 500px` instead of current `max-height` then scrollbar starts working. But I need max-height in my specific case (think about dropdown list which should automatically collapse its height if there are just a few items).

If I inspect elements, I see that when using max-height, `<div class="scrollable">` for some reason takes dimensions of the content and not of the container, therefore ng-scrollable height calculation thinks that there is already enough space and no scrollbars are required.

I think `<div class="scrollable">` should be fixed to always have the actual size of the container.

The article which might explain why 100% height does not work inside of min- and max- height:
http://www.456bereastreet.com/archive/201306/height_in_percent_when_parent_has_min-height_and_no_height/

From my first experiments, it seems that
.scrollable {
max-height: inherit;
}
works fine in Chrome, but I did not yet test other browsers.

If this works, then also min-height, min-width and max-width might be needed to support different scenarios. And maybe even width and height could be set to inherit, but I'm not sure.

Is there any way to support `max-height`?

Consider this more a feature request than a bug :)

**Comment by echa** [comment]
Hey, I had the exact same issue and don't have a solution for you. The `max-height: inherit` works in FF too which is nice.

In my apps I'm OK with only having `height` or `min-height` available on the outer container and I layout using `height: calc(100% - NNpx);` a lot. Plus I position my scrollable's  **absolute** inside the outer container. Maybe this gives you another perspective. 

Another hacky way to achieve the desired effect (if  `max-height:inherit` does not work as expected) is to manually control the outer container's height with Javascript: listen to `scrollable.dimensions` event and use `ng-style` or even manually set `elem.css({height: Math.min(contentHeight, 500)});` which is more efficient that ng-style.
