### ISSUE TITLE
Is it fully updated to 0.2.1?

### ISSUE THREAD

**Issue by progmars** [echa/ng-scrollable#23]
https://github.com/echa/ng-scrollable/blob/master/src/ng-scrollable.js
still says version 0.2.0

and
https://github.com/echa/ng-scrollable/blob/master/bower.json

says even 0.1.2

**Comment by echa** [comment]
Oh boy, you're right. I gonna fix this.

**Comment by echa** [comment]
OK, fixed in newest release 0.2.2
