### ISSUE TITLE
Do not scroll if event target of spacebar key is a checkbox

### ISSUE THREAD

**Issue by progmars** [echa/ng-scrollable#24]
When scrollable viewport contains checkboxes and I focus them with tab an press a spacebar, I expect the current checbox to change state without viewport being scrolled down.

Spacebar processing should be improved to support such scenario. Maybe there are also some other cases when we cannot scroll the viewport and kill the event but have to do some checking.

**Comment by echa** [comment]
Got your point, will be updated in the next version. As a quick workaround you can try putting `contenteditable='true'` on your input fields. In my quick test it did not work for checkboxes in FF though :(

**Comment by echa** [comment]
Ok, done. Check out v0.2.2

**Comment by progmars** [comment]
Thank you for the fast reaction. Ng-scrollable is great - it is small and simple, but it has more features than some popular over-engineered and bloated scrollbar libraries.

**Comment by echa** [comment]
Glad you like it. I kind of follow the UNIX philosophy of making small well-behaved pieces that do one job right.
