### ISSUE TITLE
scrollYAlways not working

### ISSUE THREAD

**Issue by matthieugayon** [echa/ng-scrollable#26]
Hi there, 

I am trying to get the Y scrollBar always displayed but either it seems this feature is not working ( it is setting the css display property to "inherit" but I still have to hover the content to see the scrollbar ) either I am not understanding well the point of that option, or I am missing an extra step to make it work. 

The template looks like that, I am not setting weird css classes ( display and opacity ) on the dom container neither on its parents : 

<div ng-scrollable="{scrollX:'none', scrollYAlways:'true'}" style="width: 100%; height: 100%;">

Best, 

Matthieu

**Comment by matthieugayon** [comment]
Ok, fair enough.  I don't know if it's how you intended to make this work but modifying the css and set every opacity cases to 1 solved the pb

**Comment by echa** [comment]
Yeah, you're right. Happy you found it out yourself :) 

I agree, that's an ugly feature because you need to touch both, the config option and the css to make it work as expected. I gonna think about it.
