### ISSUE TITLE
It disabled window scroll feature 

### ISSUE THREAD

**Issue by shantinath** [echa/ng-scrollable#27]
When try to scroll window after placed mouse pointer at ng-scrollable area, window scroll not working event there is nothing to scroll in my ng-scrollable area. It should scroll window in case of there are nothing to scroll or scrollbar reaches to end. Thanks in advance

**Comment by saltwoo** [comment]
Hi,

I have a very similar problem. I am implementing a mobile page and have a div that is scrollable in X axis and disabled in Y. However when I try to scroll the page itself in Y axis, if I try to scroll the page by scrolling ng-scrollable enabled div, it doesn't let me scroll the main page. 

Thanks in advance

**Comment by echa** [comment]
@saltwoo can you try the latest master and let me know if that works for you

@shantinath this request is a bit more involved and I'm still thinking about a good solution. For now, place the mouse cursor outside the scrollable area to get the desired effect.

**Comment by danscrima** [comment]
Yea I would love this feature added as well. In an ideal world, it would be nice to have the mousewheel start scrolling horizontally through a list and when it got to the end, continue scrolling the main window.

**Comment by echa** [comment]
Hey guys. This should work in the new release 0.2.4. The feature turned out to be a bit more tricky than I imagined. Let me know how it feels and make suggestions on how to improve it further.

**Comment by shantinath** [comment]
Thanks @echa Now its working fine

**Comment by jgeofil** [comment]
This works fine when there is something to scroll in the scrolling area (it reaches the end, then continues scrolling the page/parent). But I'm still having the previously stated problem when there is nothing to scroll (containerWidth > contentWidth). The event is not transmitted to the parent.

**Comment by shantinath** [comment]
Yes, @jeremy the same problem I am also facing. I was just going to post
this issue.

Shantinath Roy

**Comment by echa** [comment]
Hey guys, the issue should be fixed now. I finally found some time to dig into it. The fix was surprisingly minimal. Sorry for the long delay.
