### ISSUE TITLE
Sliders stick to mouse when using the directive anywhere on the page

### ISSUE THREAD

**Issue by mawie81** [echa/ng-scrollable#28]
We just ran into the following issue:
If you have a slider - ```<input type='range'>``` - anywhere on your page you can click it once and then the thumb will stick with your mouse.

Plunker: http://plnkr.co/edit/sWJmTWImtunqLj819XFQ?p=preview
Try to move the slider at the top of the page.
If you remove the div with ```ng-scrollable``` the slider is working again.
It doesn´t matter if the slider is inside an element with ```ng-scrollable``` or not.

**Comment by echa** [comment]
After banging my head against this and #30 I realised it's the way event handlers are attached to the document node. Fix is on the way. I don't include your patch since my other solution is more general, but thanks anyways.
