### ISSUE TITLE
Option 'useKeyboard: false' doesn't work

### ISSUE THREAD

**Issue by abodelot** [echa/ng-scrollable#3]
It seems the 'useKeyboard' option cannot be deactivate. I'm using the following:
```html
<div ng-scrollable="{useKeyboard: false}">
```

I looked up in the js source and I think this option is never handled, I cannot find any reference to 'config.useKeyboard'.

Regards,

-- Alexandre

**Comment by echa** [comment]
Thanks for pointing that out Alexandre, I simply missed implementing that option.

**Comment by abodelot** [comment]
Thank you for your fix, that was fast!
