### ISSUE TITLE
After some scrolling spy-x/spy-y does not work anymore

### ISSUE THREAD

**Issue by progmars** [echa/ng-scrollable#30]
After manual scrolling a few times, suddenly it is no longer possible to control scroll position programmatically with spy-y.

Here is a Plunker with minimal example to reproduce the issue:
http://plnkr.co/edit/Yxsux9MwkDicJcpOJhtl

**Comment by echa** [comment]
Good catch :) Fix is coming soon. This actually made me find the true problem behind #28 as well.

**Comment by echa** [comment]
Should be fixed in v0.2.3. Please give it a try and let me know if you experience further issues.

**Comment by progmars** [comment]
Thanks, now it works correctly, I could not reproduce the issue anymore.
