### ISSUE TITLE
Problem to installing master branch

### ISSUE THREAD

**Issue by xzegga** [echa/ng-scrollable#31]
I can't install master branch with bower and show this error:

	bower install ng-scrollable
	bower not-cached    git://github.com/echa/ng-scrollable.git#*
	bower resolve       git://github.com/echa/ng-scrollable.git#*
	bower ENORESTARGET  Tag/branch master does not exist

	Additional error details:
	No tags found in git://github.com/echa/ng-scrollable.git
	No branches found in git://github.com/echa/ng-scrollable.git

What can I do to install this directive without problems?

**Comment by echa** [comment]
Works on my side:
```
bower info ng-scrollable
bower ng-scrollable#*       not-cached git://github.com/echa/ng-scrollable.git#*
bower ng-scrollable#*          resolve git://github.com/echa/ng-scrollable.git#*
bower ng-scrollable#*         download https://github.com/echa/ng-scrollable/archive/0.2.3.tar.gz
bower ng-scrollable#*          extract archive.tar.gz
bower ng-scrollable#*         resolved git://github.com/echa/ng-scrollable.git#0.2.3

{
  name: 'ngScrollable',
  version: '0.2.3',
  homepage: 'https://github.com/echa/ng-scrollable',
  authors: [
    'Alexander Eichhorn <alex@kidtsunami.com>'
  ],
  description: 'Superamazing scrollbars for AngularJS',
  main: [
    'min/ng-scrollable.min.css',
    'min/ng-scrollable.min.js'
  ],
  license: 'MIT',
  ignore: [
    '**/.*',
    'node_modules',
    'bower_components',
    'test',
    'tests'
  ],
  dependencies: {
    angular: '*'
  }
}

Available versions:
  - 0.2.3
  - 0.2.2
  - 0.2.0
  - 0.1.2
  - 0.1.1
  - 0.1.0
You can request info for a specific version with 'bower info ng-scrollable#<version>'
```
You shouldn't have to do anything more. Maybe [this](http://stackoverflow.com/questions/24234063/how-to-resolve-bower-issue-enorestarget-tag-branch-master-does-not-exist) helps
