### ISSUE TITLE
Viewport is not scrolled in both directions when changing both spy-x and spy-y at once

### ISSUE THREAD

**Issue by progmars** [echa/ng-scrollable#32]
Sorry to bother again, but here is one more simple case which does not work as expected:
http://plnkr.co/edit/XwMjHTs3OAWXnJhTtBxs

It seems, some workaround is required (maybe even $digest or $timeout in the right place would work) to make it possible to update both x and y positions in one call.

**Comment by echa** [comment]
Oh boy, it's fixed. Your spy variables are readable and writeable. When the first watcher on spyX fired it triggered a scroll which in turn overwrote both spies, spyX to the new and spyY to the previous value. Now, writing to spy variables happends async, after all watchers have been processed.
