### ISSUE TITLE
Feature suggestion - mousweheel speed normalization across browsers

### ISSUE THREAD

**Issue by progmars** [echa/ng-scrollable#33]
I noticed that on Mozilla Firefox scrolling is much slower than on Chrome and IE  browsers (about 6 times in some larger lists). It's not a problem with ng-scrollbar, but with scrolling in Firefox in general.

It would be great to have optional ability to normalize scroll speed. Maybe the following StackOverflow topic will give some ideas:
http://stackoverflow.com/questions/5527601/normalizing-mousewheel-speed-across-browsers

It is tricky and I'm not asking to implement full support, but at least it might be great to smooth out some huge differences across some browsers.

Ideally, there should be some way to switch on/off the normalization globally for the entire application through some Angular ConfigurationProvider (you could also add other global settings there, e.g. global wheelSpeed, SlackSpace etc.).

**Comment by echa** [comment]
Thanks, I'll look into it.

**Comment by progmars** [comment]
So, I studied the topic a bit and tested FF, IE, Chrome and found that scrolling works 100% correctly only on Chrome. 
There is one common issue with FF and IE -  although wheel event has `shiftKey=true`, it does not set deltaX to the delta, but deltaY is set.
And another issue with FF - it is scrolling not by pixels, but by lines - `deltaMode=1`. This explains why it ng-scrollable so slow on FF.

I added a quick workaround for both these issues:

```
        handleWheel = function (e) {
            
          // with jquery use e.originalEvent.deltaX!!!
          var e = e.originalEvent || e;
      
          // inconsistent e.deltas
          // on Chrome - +/-100 .. , -0 if no move; 
          // supports both vertical and horizontal out-of-the-box
          // (while holdingh Shift); 
          // scrolling speed increments by 100; not easy to step up
          // deltaMode always 0, shiftKey reacts correctly
          // 
          // on Firefox - +/-3 .., 0 if no move; horizontal always 0;
          // scrolling speed increments by 3; not easy to step up;
          // deltaMode always 1, shiftKey reacts correctly
          // 
          // on IE - +/-56 .., 0 if no move; horizontal always 0;
          // scrolling speed increments by 56; easy to step up
          // deltaMode always 1, shiftKey reacts correctly
          
          // have to clone deltas because props are read-only
          var deltas = {
              deltaX : e.deltaX,
              deltaY : e.deltaY
          };
          
          if(config.normalizeScrollWheelBehavior){
            // abs for -0, < 0.1 for non-integer detection
            if(e.shiftKey == true && Math.abs(deltas.deltaX) < 0.1){ 
                // switch places
                deltas.deltaX =  deltas.deltaY;
                deltas.deltaY = 0;
            }

            // a quick fix - compensate for deltaMode=1 on FF
            // and missing shiftKey automatic processing on IE and FF
            if(e.deltaMode == 1){ // DOM_DELTA_LINE, scroll by line 
                // lucky guess - multiply to reach ~75.0 per step on FF, 
                // that is, somewhere between IE and Chrome
                deltas.deltaX *= 25.0;
                deltas.deltaY *= 25.0;
            }
        }
      
///// no changes after this point
         var deltaX = deltas.deltaX * config.wheelSpeed,
              deltaY = deltas.deltaY * config.wheelSpeed;
```

After that I tested with FF, IE, Chrome, Opera - seems to work fine. Sorry, no Safari available and I'm not sure how it will work on Linux and Mac.

**Comment by echa** [comment]
Thanks for the update. What a mess this Web plus Javascript world still is. I have only a very limited scope for testing this since I only work on OSX and iOS/Android without a real wheel-mouse. The best Stackoverflow comments points to an implementation found in FB React (https://github.com/facebook/fixed-data-table/blob/master/src/vendor_upstream/dom/normalizeWheel.js) which I consider using.

Right now I included a quick fix in master which transforms FF's LINE deltaMode into pixels based on the elements font-size.

**Comment by echa** [comment]
Check out the new release 0.2.4. It works a bit better now, but it's still not as smooth as I like it to be. I checked with FF/Chrome/Edge in Windows 10 running inside a VM.
