### ISSUE TITLE
In some specific cases ng-scrollable gets stuck when page loads

### ISSUE THREAD

**Issue by progmars** [echa/ng-scrollable#36]
I just found another weird case when for some reason mouse wheel on ng-scrollable does not work right after page loads, if spy-y is enabled:
http://plnkr.co/edit/xF30Qp3q3c1DqEVitBcb

This is really strange. For some reason it works just fine if I use ng-repeat instead of some static text. And it suddenly starts working again if I drag the scrollbar down manually (sometimes it does not react immediately, you have to try a few times) or if I change spy-y variable programmatically.

**Comment by progmars** [comment]
Oh, I found the reason - this happens if I don't have spy variables defined on the scope - then scroll functions receive `undefined` value and all hell breaks lose with NaNs propagated through  calculation.

The fix is simple:

```
            $scope.$watch(attrs[attr], function (val) {
              // protect against nulls and undefineds, which are possible
              // on first request if spy variables haven't been set 
              // on outer scope
              val = val || 0;
```

**Comment by echa** [comment]
Thanks for finding this. Will include your fix in the next version.
