### ISSUE TITLE
Problen when working on devices with mouse and touch screen

### ISSUE THREAD

**Issue by dape48** [echa/ng-scrollable#38]
- The directive don't registers handlers for mouse events on touch screen devices, only for touch events, neither for wheel, mouseenter, mouseleave and keydown events. Therefore you can't use mouse wheel (or touchpad on labtops) to scroll when using touch screens. 

- When the ng-scrollable component contains clickable components they will work clicking with mouse on it but not touchin because the touchstart event is prevented.

I have been trying to solve this isues, and it seems to work properly. Firstly I changed 'registerHandlers'/'unregisterHandlers' functions to always register/unregister handlers for wheel, mouseenter, mouseleave and keydown events. Then I changed 'onMouseDownX'/'onMouseDownY' functions to dont' prevent touchstart events. 

Thanks!!

**Comment by echa** [comment]
Hey Dape48, thanks for reporting. Please try the new release 0.2.4. Hope this works for you now.
