### ISSUE TITLE
Stop scroll propagation to parent

### ISSUE THREAD

**Issue by Allaoua9** [echa/ng-scrollable#42]
is there anyway to prevent the scrolling of the parent element when the scrolls begin, or when the scroll bar arrives at the bottom ?

**Comment by echa** [comment]
This should work in the latest release. Can you please check if the demo at http://echa.github.io/ng-scrollable/ does what you intend? On which type of device and which browser did you check?

**Comment by Allaoua9** [comment]
@echa  thank you for responding so fast.

I tried it on chrome and firefox. When scrolling with the mouse wheel, the scrolling get propagated to the scrollable parent element (in the demo the parent is the document window) once the scroll bar arrives to the bottom.

a similar issue is discussed here with more details: http://stackoverflow.com/questions/5802467/prevent-scrolling-of-parent-element

**Comment by echa** [comment]
Ah, now I understand wat you mean. This was a new feature that people asked for in #27 

I can add a configuration option to disable this feature. Is this what you need?

**Comment by Allaoua9** [comment]
Yes, that's it !

It would be great if there was a configuration option to enable/disable that.

Thanks @echa you've done a great job ! this module is awesome keep it up and Good luck.

**Comment by echa** [comment]
Hey Allaoua, the configuration option to control wheel event propagation is finally there. It's called `preventWheelEvents`. See the README for details. Sorry for the long delay.
