### ISSUE TITLE
Max width, max height style bug.

### ISSUE THREAD

**Issue by je3f0o** [echa/ng-scrollable#45]
Hi, thank you for this awesome module. I'm using it in my application right now.
But I think I found a bug. I wonder why you did this. Maybe you did for some reason.
Anyway, in your `refresh` function `dom.el[0].clientWidth`, `dom.el[0].clientHeight` is not giving me right size when I'm using `<any ng-scrollable style="max-height: 400px;">...</any>`.
Because `dom.el` is `.scrollable` class and `.scrollable` class styled `width: 100%; height: 100%;`.
It should be always same size with content's size. (never scrollable)
So I changed `dom.el[0].clientHeight` to `elem[0].clientHeight` it works just fine.
[line: 287 and 288 in current commit](https://github.com/echa/ng-scrollable/blob/master/src/ng-scrollable.js#L287)

**Comment by echa** [comment]
Should work now.
