### ISSUE TITLE
scroll conflicted with browser native

### ISSUE THREAD

**Issue by wujie520303** [echa/ng-scrollable#47]
when I used **ng-scrollable** into a popup layer with angular plugins of **ng-pageslide**. firstly, I found the function of **ng-scrollable** isn't active, untill i resized the window or the pop element wrapper. secondly, when I scroll element of popup layer, I found if the body's content has scrollbar, both of them will trigger 'scroll' action.

**Comment by echa** [comment]
Thanks for reporting. 

Your first problem is related to #16 and a #44 is a pending pull request which I still need to work in. For now you can use the workaround described in #16 .

The scroll propagation issue is related to #27 and #42. In the latest release ngScrollable does not cancel scroll events when the scroll position is already at the content edge. Some folks felt scrolling is more natural when delegated to the outside container (e.g. the body). In your case it seems a config option to disable event propagation alltogether is the best choice. I'm working on that too.

**Comment by echa** [comment]
While re-reading your description I got the impression I misunderstood the second part. If this is still important to you, can you make a stripped-down example showing your second problem(on jsfiddle or somewhere else? 

After my latest changes ng-scrollable compiles before the container content which should solve  at least your first problem.
