### ISSUE TITLE
Rendering issue in Microsoft IE11 and MIcrosoft Edge

### ISSUE THREAD

**Issue by Tigran-Harutyunyan** [echa/ng-scrollable#48]
Hi
First of all let me thank you for your efforts. I really enjoyed implementing ng-scrollable until found out the rendering problem with latest Microsoft browsers. (See demo page http://echa.github.io/ng-scrollable/ in them.)
Any hope with the rendering issue? Is the problem anyhow connected with translate3d or js related ?
Thanks in advance

**Comment by echa** [comment]
Hey Tigran, I'm not sure what rendering issue you are refering to. Windows is not my native platform and I can only test IE Edge in a virtual machine. From there it seems the CSS transition in combination with translate3d is not as smooth as in other browsers. Is this what you mean?

**Comment by Tigran-Harutyunyan** [comment]
Thank you very much for your reply echa! 
I have tested on a several machined running Windows 10. In latest MS IE11 and  Edge browsers whenever I drag scrollbar as mentioned in screenshot you`ll notice the erratic behavior. Screen recorder wasn`t able to record that problem. Chrome and Firefox  scroll correctly.  I tried to scroll ul with the li items. The same problem with above mentioned browsers.
Hopefully you`ll find a windows machine to reproduce the problem.
Thanks for your efforts!
![reluctant-drag](https://cloud.githubusercontent.com/assets/5655756/16456045/8ec9c6ca-3e27-11e6-944d-64996de0d76b.png)

**Comment by echa** [comment]
Just pushed some changes to master that should help prevent this issue.

**Comment by Tigran-Harutyunyan** [comment]
Hi Alexander. Yes. The issue is noticed in IE11 and MS Edge running MS
Windows 10.
In this testing site I `m able to reproduce the issue.
hopefully it helps

**Comment by Tigran-Harutyunyan** [comment]
Sorry forgot the link. https://www.browserling.com/internet-explorer-testing
