### ISSUE TITLE
Independent scroll

### ISSUE THREAD

**Issue by michelem09** [echa/ng-scrollable#49]
Is there a way to have the scrollable div independent by the body window?

I mean exactly like the demo in https://noraesae.github.io/perfect-scrollbar/

So if you are with the mouse inside the scrollable div and you scroll reaching the end of it you don't continue to scroll the body until you leave the div with them mouse.

**Comment by echa** [comment]
Hi. It will come as a configuration option in the next release. A few releases back this used to be the default behaviour. Then a few people asked for scrolling to propagate to the body so I got convinced and switched default to this mode.

**Comment by michelem09** [comment]
As option is really good, do you think you can release it quickly? Or can I know where to put my hand to revert the original behaviour?
Many thanks

**Comment by echa** [comment]
Sure. It has been on the request list for too long, so here we go :) 

The recent master branch contains a new boolean option `preventWheelEvents`. The default is the native browser behaviour similar to `overflow:scroll`. To get what you are looking for set the option to false.

**Comment by michelem09** [comment]
Thanks man!

**Comment by echa** [comment]
Ups, you should set the option to `true` in your case. My bad. Default is `false`
