### ISSUE TITLE
bower: Package ng-scrollable not found

### ISSUE THREAD

**Issue by jvanhees** [echa/ng-scrollable#5]
bower install ng-scrollable --save-dev gives a bower error:
bower                        ENOTFOUND Package ng-scrollable not found

When I try to manually install the package with a URL, I get the following error:
Kingsguard:bbvms JVH$ bower install https://github.com/echa/ng-scrollable.git --save-dev
bower ng-scrollable#*       not-cached https://github.com/echa/ng-scrollable.git#*
bower ng-scrollable#*          resolve https://github.com/echa/ng-scrollable.git#*
bower ng-scrollable#*           cached https://github.com/echa/ng-scrollable
bower ng-scrollable#*         validate https://github.com/echa/ng-scrollable#*
bower ng-scrollable#*         checkout 0.1.0
bower ng-scrollable#*       EMALFORMED Failed to read <tempdit>/bower/ng-scrollable-75826-1zMeig/bower.json

Additional error details:
Unexpected token ]

Registering the package with bower does not work either, it does not accept the JSON (though the JSON itself is correct..).

**Comment by jvanhees** [comment]
Solved using "https://github.com/echa/ng-scrollable.git#master". Should create a new tag with the correct Bower.json. Perhaps find a workaround to still register it at bower?

**Comment by echa** [comment]
Ahh .. that's it. Thanks for the idea to fix it! I'll make a new release then.
