### ISSUE TITLE
2-finger trackpad scroll doesn't seem to work in IE

### ISSUE THREAD

**Issue by intowhite** [echa/ng-scrollable#54]
Click-drag on the bar still works, mousewheel still works. Sorry in advance.

**Comment by echa** [comment]
Hmm, could have different many reasons. Have you by any chance disabled touch actions in CSS `-ms-touch-action: none` for any of the scrollable's parent elements?

**Comment by echa** [comment]
Looks like an Edge bug: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7134034/

Reason is Edge does not send wheel events when scrolling with 2 fingers. One reason why I intentionally left out any MS browser from the list of supported browsers.

If you find a solution, I'd highly welcome a PR.

Closing for now.
