### ISSUE TITLE
Vertical scroll doesn't work

### ISSUE THREAD

**Issue by campellodavide** [echa/ng-scrollable#56]
Hi, thanks for this good component.
I'm using the orizontal scroll in a ng-table like this:
```
<div ng-scrollable="{scrollX:'none',scrollY:'left'}" style="width: 300px;">
    <table" ng-table="model.tableParams" class="table table-condensed table-hover" >
        <tr ng-repeat="row in $data" >
             <td data-title="'...'">
                {{data}}
            </td><td data-title="'...'">
                {{data}}
            </td><td data-title="'...'">
                {{data}}
            </td><td data-title="'...'">
                {{data}}
            </td><td data-title="'...'">
                {{data}}
            </td>
        </tr>
    </table>
</div>
```

I have a lot of column and a maximum size of 300px so i want a orizontal scroll but I want use the browser's default vertical scroll. 
The orizontal work good but the vertical not. If the mouse is over the div with the ng-scrollable the scroll doesn't move.
Can anyone help me?
Thanks in advance

**Comment by echa** [comment]
should be fixed in the upcoming release
