### ISSUE TITLE
ng-scrollable="{ scrollYAlways:true }" not works

### ISSUE THREAD

**Issue by YeisonVelez11** [echa/ng-scrollable#59]
I need show always the axis y scroll.. but nothing happens..

**Comment by echa** [comment]
What did you do? I need a code example to help you here.

**Comment by echa** [comment]
I assume this is a CSS issue that you should change in your app. See the CSS classes for `.scrollable .scrollable-bar` and their opacity setting. You can override these if you need the scrollbar to show all the time. If you don't see scrollbars at all, not even when hovering over the content, you may have forgot to load the ng-scrollable module in your Angular app dependencies.

By default scrollbars have an opacity of zero unless your mouse pointer **hovers** over the scrollarea or you **actively scroll**. Scrollbars are also hidden when the content is smaller than the scrollable container to mimick the same behaviour you get with normal browser scrolling. The `scrollYAlways` option only disables auto-hiding based on content size.
