### ISSUE TITLE
Horizontal scroll blocking natural body scroll

### ISSUE THREAD

**Issue by iuliaL** [echa/ng-scrollable#61]
Check out this homepage http://solascriptura.ro/
When hovering over the scroll-container the page scrolls just horizontally
Maybe this behavior is the desired one, but I've found this commit
https://github.com/echa/ng-scrollable/commit/7c3cfa4aac8f081294e6e6505d955ba7615d9c66
where on line 601 the if block is commented. If I uncomment that block I do get the natural vertical page scroll.
(maybe by the time you see this issue the page will be updated and you won't see the issue as a demo)
Thank you very much for this useful component

**Comment by echa** [comment]
Hey, the quick fix for you would be to add `scrollY:'none'` to your horizontal ngScrollable. 

Vertical scrolling is enabled by default and the older version you use does not read the height of your content correctly (so it does not know when the end is reached). You can update to the latest master branch if you like.

Feel free to reopen if this did not solve your problem.
