### ISSUE TITLE
Scroll To 

### ISSUE THREAD

**Issue by sirdowan** [echa/ng-scrollable#66]
Hi, 

Firstly, I really like your plugin! :)

I'm using ng-scrollable to display a youtube playlist (through YT data API). I would like to scroll to the currently playing video inside the playlist. I have added an 'active' class to the current video, but can't scroll to it. I created a hack, so when the user hits next for example: 
`$rootScope.$broadcast('change-scroll-pos', $scope.selectedIndex * angular.element('.mainScroll .activ').outerHeight() );`

and then inside the scroller controller:

` $scope.$on('change-scroll-pos', function(event, position) {        
        setTimeout(function () {
            $scope.$broadcast('scrollable.scroll.y', position);
        }, 300)
    });`

Sadly the calculation is not perfect, because the outerHeight() gives back an integer, and the actual height is 0.3px bigger than it gives back. Any ideas on how I should approach this? 

Thanks a bunch!

**Comment by echa** [comment]
Hi,

I'm happy you find ng-scrollable useful. 

What I do to auto-scroll an element into focus is to emit a `focus` event on the element itself. ng-scrollable already watches for focus events, so you don't have anything else to do. It's for example working when you tab through form fields (forward and backwards).

To easily trigger focus events based on data properties I use a custom directive:
```
angular.module('myapp').directive('focus', function () {
  return {
    link: function(scope, element, attrs) {
      scope.$watch(attrs.focus, function (value) {
        if (!!value) {
          scope.$applyAsync(function() { element[0].focus(); });
        }
      }, true);
    }};
});
```
and trigger focus by setting a child property (e.g. $selected) to a truthy value. The template would look like so
```
<div ng-scrollable>
  <ul ng-repeat="item in list">
    <li focus="item.$selected"></li>
  </ul>
</div>
```
You might want to be more sophisticated in choosing the trigger condition in your own focus directive to make it debounce correctly etc.

Hope that helps.
