### ISSUE TITLE
Control the X,Y position dynamically

### ISSUE THREAD

**Issue by harm-less** [echa/ng-scrollable#7]
Hello,

I was playing with your directive just now and I was wondering how I can control the X,Y position of the container from outside of the directive. To my surprise that is not possible with the current directive, or did I miss something?

It would be a great addition since this would allow for more control. I'm trying to create a scroll-able thumbnail list, and your directive suits my purposes quite well if this feature would be available.

Thanks in advance,
Harm

**Comment by echa** [comment]
Her Harm

You're right. This is not supported right now. What exactly do you have in mind? 

I can add scrolling to content edges (top, right, left, bottom) with little effort. If you think of scrolling to anchors (e.g. a positioned HTML element inside the container) things get a litte more complicated.

**Comment by harm-less** [comment]
Sounds good! Well, besides the egde anchors, I think the X, Y positions in pixels should be fairly simple too (as far as I can see from the source). 

Perhaps in the directive you check if the element ng-scrollable is applied to has an attribute of "scroll-x". If so, you can evaluate and watch/bind the value to a method in your directive that in turn calls the "scrollX" method (on line 167) in your directive. And the "pos" parameter value is the returned value from the binded method. 

Perhaps this makes it more clear:
<div ng-scrollable scroll-x="manualScrollX()">

I presume you don't want to make an isolated scope (I wouldn't), so checking the attribute sounds like the best method. I think the datepicker from Bootstrp UI solves this pretty good:
https://github.com/angular-ui/bootstrap/blob/master/src/datepicker/datepicker.js

**Comment by harm-less** [comment]
I added a pull request to add this feature

**Comment by echa** [comment]
Wow. That was fast! I didn't have time to work on the feature yesterday. Very much appreciated.

**Comment by harm-less** [comment]
You're welcome. Will you create a new (bower) version from this pull after you tested it yourself? I can't wait to use it you see ;)

**Comment by echa** [comment]
Done. I changed the parameter passing to use $parse and setters so you can use different types of expressions. In my tests it did not always update the $scope.posX/Y on the outside controller/scope when first scrolling on the touchpad/mouse and then using the external scroll buttons. 

I also renamed the new attributes to spy{X|Y} to avoid confusing names with configuration parameters. 

Let me know if things work for you.
