### ISSUE TITLE
Show scrollbar by deault without mousewheel event.

### ISSUE THREAD

**Issue by balaameex** [echa/ng-scrollable#9]
Please update me is there any option to show the scroll bar by default , with out triggering the mouse wheel event.

**Comment by sandelius** [comment]
@balaameex In the example http://echa.github.io/ng-scrollable/ the scrollbar is shown on hover

**Comment by echa** [comment]
@balaameex maybe you found the solution already, but anyways .. you can show scrollbars with
```.scrollable .scrollable-bar,
.scrollable:hover .scrollable-bar {
    opacity: 1;
}```
in your own css after including ngscrollable's css. As an alternative, change the opacity setting in the ngscrollable css.

**Comment by sandelius** [comment]
@echa Your example didn't work

**Comment by echa** [comment]
Hmm, if you want to show scrollbars even if the content is smaller than the container, set `{scrollYSlackSpace: -Y, scrollXSlackSpace: -X}` when configuring the directive. Note: X and Y are negative numbers. They should correspond to the size of your container. If in doubt, set them to -10000 or even lower.
